services:
  poker-solo-rpg:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      # Uncomment these lines for development mode
      # - ./src:/app/src
      # - ./public:/app/public
      # Mount the nginx configuration if needed
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    # For development mode, use a different command
    # command: npm run dev -- --host 0.0.0.0
    # For development, use a different image
    # image: node:18-alpine
    # working_dir: /app
